# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# git push origin --delete v0.1.0
# git tag --delete v0.1.0
# git tag v0.1.0 -m "version bump"
# git push origin --tags

name: Publish to npm

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - if: ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}
        name: Publish to npmjs
        run: |
          pnpm install --frozen-lockfile --ignore-scripts
          pnpm publish --ignore-scripts --no-git-checks
